[package]
name = "embassy-imxrt-examples"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
cortex-m = { version = "0.7.7", features = [
    "inline-asm",
    "critical-section-single-core",
] }
cortex-m-rt = "0.7.3"
defmt = "0.3.6"
defmt-rtt = "0.4.0"
panic-probe = { version = "0.3.1", features = ["print-defmt"] }
embassy-imxrt = { version = "0.1.0", path = "../../", features = ["defmt"] }
embassy-executor = { version = "0.5.0", features = [
    "arch-cortex-m",
    "executor-thread",
] }
embassy-sync = "0.6.0"
embassy-futures = "0.1.1"
futures = { version = "0.3.30", default-features = false, features = [
    "async-await",
] }

[profile.dev]
opt-level = 0      # Enable basic optimizations to preven super large binaries
codegen-units = 16
debug = true
lto = false

# Set the default for dependencies to optimized even for debug build to prevent super large binaries
[profile.dev.package."*"]
opt-level = "s"

[profile.release]
opt-level = "s"   # optimize for size
codegen-units = 1 # better optimizations
debug = true      # symbols are nice and they don't increase the size on Flash
lto = true        # better optimizations
