
# cargo-vet audits file

[[audits.defmt-rtt]]
who = "Felipe Balbi <febalbi@microsoft.com>"
criteria = "safe-to-deploy"
version = "1.0.0"
notes = "defmt-rtt is used for all our logging purposes. Version 1.0.0 merely stabilizes what was already available previously."

[[audits.embassy-executor-timer-queue]]
who = "Felipe Balbi <febalbi@microsoft.com>"
criteria = "safe-to-deploy"
version = "0.1.0"

[[audits.embassy-time-queue-utils]]
who = "Felipe Balbi <febalbi@microsoft.com>"
criteria = "safe-to-deploy"
version = "0.3.0"

[[audits.mimxrt600-fcb]]
who = "Jerry Xie <jerryxie@microsoft.com>"
criteria = "safe-to-deploy"
delta = "0.2.1 -> 0.2.2"

[[audits.mimxrt633s-pac]]
who = "Felipe Balbi <febalbi@microsoft.com>"
criteria = "safe-to-deploy"
version = "0.4.1"
notes = "New version of mimxrt633s-pac merely introduces safe enum variants for IRULESTAT register. No new unsafe blocks are introduced."

[[audits.static_cell]]
who = "jerrysxie <jerryxie@microsoft.com>"
criteria = "safe-to-run"
delta = "2.1.0 -> 2.1.1"
