# This workflow executes HW tests on an NXP RT600 EVK.
# NOTE: for now it simply executes a build on the self-hosted test runner PC.
#
permissions:
    contents: read
on:
    workflow_dispatch
  #  push:
  #    branches: [main]
name: hwtest-automation
jobs:
    hwtest-automation:
      runs-on: self-hosted
      name: ${{ matrix.target }}
      strategy:
        matrix:
          target: [thumbv8m.main-none-eabihf]
      steps:
        - uses: actions/checkout@v4
          with:
            submodules: true
        - name: install stable
          uses: dtolnay/rust-toolchain@stable
        - name: rustup target add ${{ matrix.target }}
          run: rustup target add ${{ matrix.target }}
        - name: cargo build
          run: cargo build --target ${{ matrix.target }}
        - name: change directory
          run: |
            cd examples\rt685s-evk\src\tests
            .\test.ps1
            
