# This workflow executes HW tests on an NXP RT600 EVK.
# NOTE: for now it simply executes a build on the self-hosted test runner PC.
#
permissions:
    contents: read
on:
  push:
    branches: [main]
  pull_request:

env:
 BRANCH_NAME: ${{ github.head_ref || github.ref_name }} 
name: hwtest-automation
jobs:
    hwtest-automation:
      runs-on: self-hosted
      name: Run integration tests
      strategy:
        matrix:
          target: [thumbv8m.main-none-eabihf]
      steps:
        - uses: actions/checkout@v4
          with:
            submodules: true
        - name: run tests
          run: |
            cd examples\rt685s-evk
            .\run_tests.ps1 -Arg ${{env.BRANCH_NAME}}
            
